name: Build and Publish

# configure manual trigger
on:
    push:
        branches: [ "js" ]
    pull_request:
        branches: [ "js" ]
    workflow_dispatch:

jobs:
    build:
        name: Test and Build
        runs-on: ubuntu-latest
        steps:

            # Setup Java 1.8 environment for the next steps
            - name: Setup Java
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            # Check out current repository
            - name: Fetch Sources
              uses: actions/checkout@v2

            # Build application
            - name: Test and Build
              run: ./gradlew :js:build

            #- name: Copy "uninstantiated" file over (workaround for now)
            #  run: cp web/build/compileSync/wasm/main/productionExecutable/kotlin/canvasmultiplatform.uninstantiated.mjs web/build/dist/wasm/productionExecutable

            # If main branch update, deploy to gh-pages
            - name: Deploy
              if: github.ref == 'refs/heads/js'
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: js/build/distributions # The folder the action should deploy.
                  CLEAN: true # Automatically remove deleted files from the deploy branch